# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topskills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='count',
        ),
    ]
